export const PATIENT_GET_PATIENTS_LIST = "PATIENT_GET_PATIENTS_LIST";
export const PATIENT_GET_PATIENTS_LIST_SUCCESS =
  "PATIENT_GET_PATIENTS_LIST_SUCCESS";
export const PATIENT_GET_PATIENTS_LIST_FAILURE =
  "PATIENT_GET_PATIENTS_LIST_FAILURE";

export const PATIENT_DELETE_PATIENT = "PATIENT_DELETE_PATIENT";
export const PATIENT_DELETE_PATIENT_SUCCESS = "PATIENT_DELETE_PATIENT_SUCCESS";
export const PATIENT_DELETE_PATIENT_FAILURE = "PATIENT_DELETE_PATIENT_FAILURE";

export const PATIENT_ADD_NEW_PATIENT = "PATIENT_ADD_NEW_PATIENT";
export const PATIENT_ADD_NEW_PATIENT_SUCCESS =
  "PATIENT_ADD_NEW_PATIENT_SUCCESS";
export const PATIENT_ADD_NEW_PATIENT_FAILURE =
  "PATIENT_ADD_NEW_PATIENT_FAILURE";

export const PATIENT_UPDATE_PATIENT = "PATIENT_UPDATE_PATIENT";
export const PATIENT_UPDATE_PATIENT_SUCCESS = "PATIENT_UPDATE_PATIENT_SUCCESS";
export const PATIENT_UPDATE_PATIENT_FAILURE = "PATIENT_UPDATE_PATIENT_FAILURE";

export const PATIENT_GET_PATIENT_STATISTICS = "PATIENT_GET_PATIENT_STATISTICS";
export const PATIENT_GET_PATIENT_STATISTICS_SUCCESS =
  "PATIENT_GET_PATIENT_STATISTICS_SUCCESS";
export const PATIENT_GET_PATIENT_STATISTICS_FAILURE =
  "PATIENT_GET_PATIENT_STATISTICS_FAILURE";

export const PATIENT_GET_PATIENT_BY_ID = "PATIENT_GET_PATIENT_BY_ID";
export const _GET_PATIENT_BY_ID_SUCCESS = "PATIENT_GET_PATIENT_BY_ID_SUCCESS";
export const PATIENT_GET_PATIENT_BY_ID_FAILURE =
  "PATIENT_GET_PATIENT_BY_ID_FAILURE";
