export const RECORDS_ADD_NEW_RECORD = "RECORDS_ADD_NEW_RECORD";
export const RECORDS_ADD_NEW_RECORD_SUCCESS = "RECORDS_ADD_NEW_RECORD_SUCCESS";
export const RECORDS_ADD_NEW_RECORD_FAILURE = "RECORDS_ADD_NEW_RECORD_FAILURE";

export const RECORDS_UPDATE_RECORD = "RECORDS_UPDATE_RECORD";
export const RECORDS_UPDATE_RECORD_SUCCESS = "RECORDS_UPDATE_RECORD_SUCCESS";
export const RECORDS_UPDATE_RECORD_FAILURE = "RECORDS_UPDATE_RECORD_FAILURE";
