export const DOCTOR_GET_DOCTORS_LIST = "DOCTOR_GET_DOCTORS_LIST";
export const DOCTOR_GET_DOCTORS_LIST_SUCCESS = "DOCTOR_GET_DOCTORS_LIST_SUCCESS";
export const DOCTOR_GET_DOCTORS_LIST_FAILURE = "DOCTOR_GET_DOCTORS_LIST_FAILURE";

export const DOCTOR_ADD_DOCTOR = "DOCTOR_ADD_DOCTOR";
export const DOCTOR_ADD_DOCTOR_SUCCESS = "DOCTOR_ADD_DOCTOR_SUCCESS";
export const DOCTOR_ADD_DOCTOR_FAILURE = "DOCTOR_ADD_DOCTOR_FAILURE";

export const DOCTOR_DELETE_DOCTOR = "DOCTOR_DELETE_DOCTOR";
export const DOCTOR_DELETE_DOCTOR_SUCCESS = "DOCTOR_DELETE_DOCTOR_SUCCESS";
export const DOCTOR_DELETE_DOCTOR_FAILURE = "DOCTOR_DELETE_DOCTOR_FAILURE";

export const DOCTOR_GET_DOCTOR_BY_ID = "DOCTOR_GET_DOCTOR_BY_ID";
export const DOCTOR_GET_DOCTOR_BY_ID_SUCCESS = "DOCTOR_GET_DOCTOR_BY_ID_SUCCESS";
export const DOCTOR_GET_DOCTOR_BY_ID_FAILURE = "DOCTOR_GET_DOCTOR_BY_ID_FAILURE";

export const DOCTOR_EDIT_DOCTOR = "DOCTOR_EDIT_DOCTOR";
export const DOCTOR_EDIT_DOCTOR_SUCCESS = "DOCTOR_EDIT_DOCTOR_SUCCESS";
export const DOCTOR_EDIT_DOCTOR_FAILURE = "DOCTOR_EDIT_DOCTOR_FAILURE";
