export const DOCTOR_GET_DOCTORS_LIST = "DOCTOR_GET_DOCTORS_LIST";
export const DOCTOR_GET_DOCTORS_LIST_SUCCESS =
  "DOCTOR_GET_DOCTORS_LIST_SUCCESS";
export const DOCTOR_GET_DOCTORS_LIST_FAILURE =
  "DOCTOR_GET_DOCTORS_LIST_FAILURE";
